# Generated by Django 4.2.1 on 2023-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edges', models.JSONField(blank=True, null=True, verbose_name='Edges')),
                ('nodes', models.JSONField(verbose_name='Nodes')),
            ],
        ),
    ]
