# Generated by Django 4.2.1 on 2023-06-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcecodes', '0003_sourcecode_location'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRequirements',
            new_name='UserRequirement',
        ),
    ]
