# Generated by Django 4.2.1 on 2023-06-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_rename_userrequirements_userrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequirement',
            name='edges',
            field=models.JSONField(null=True, verbose_name='Edges'),
        ),
    ]
