# Generated by Django 4.2.1 on 2023-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_alter_userrequirement_edges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequirement',
            name='edges',
            field=models.JSONField(blank=True, default=[], verbose_name='Edges'),
            preserve_default=False,
        ),
    ]
