# Generated by Django 4.2.1 on 2023-06-05 12:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcecodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecode',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
